export default [
    /^name$/,
    /^package$/,
    /^windows\.[0-9]+$/,
    /^windows\.[0-9]+\.title$/,
    /^windows\.[0-9]+\.position\.\w+$/,
    /^windows\.[0-9]+\.tabs$/,
    /^windows\.[0-9]+\.tabs\.[0-9]+\.label$/,
    /^windows\.[0-9]+\.tabs\.[0-9]+\.content$/,
    /^windows\.[0-9]+\.tabs\.[0-9]+\.pane$/,
    /^windows\.[0-9]+\.layout\.panes\.orientation$/,
    /^windows\.[0-9]+\.layout\.panes\.percentage$/,
    /^windows\.[0-9]+\.layout(\.panes\.pane[12])*\.content$/,
    /^windows\.[0-9]+\.layout(\.panes\.pane[12])*\.content_type$/,
    /^windows\.[0-9]+\.layout(\.panes\.pane[12])*\.leaf_type$/,
    /^windows\.[0-9]+\.layout(\.panes\.pane[12])+\.panes\.orientation$/,
    /^windows\.[0-9]+\.layout(\.panes\.pane[12])+\.panes\.percentage$/,
]
